/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nthan
 */

package dictionnary;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.net.Socket;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;

import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
public class Dictionnary extends javax.swing.JFrame {
    
    
    final static int EN_VN = 1; // translate from English to Vietnamese
    final static int VN_EN = 2; //translate from Vietnamese to English
    static int Translation = 1; // 
    static String KeyWord = "";
    static ProcessWord Obj;
    
    public Dictionnary() {
        initComponents();
        setTitle("Dictionnary");
        setResizable(false);
        // override luu ky tu yeu thich xuong file trong qua trinh windows dang tat
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                Obj.SaveFileListWordLove();
                Obj.SaveHistory();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_backroud = new javax.swing.JPanel();
        tf_KeyWord = new javax.swing.JTextField();
        cb_SelectLanguage = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textarea_trans = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        list_Suggest = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        btn_Search = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 255));

        tf_KeyWord.setToolTipText("Enter your word");
        tf_KeyWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_KeyWordActionPerformed(evt);
            }
        });
        tf_KeyWord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_KeyWordKeyReleased(evt);
            }
        });
        tf_KeyWord.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                tf_KeyWordVetoableChange(evt);
            }
        });

        cb_SelectLanguage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English-Vietnamese", "Vietnamese - English" }));
        cb_SelectLanguage.setName("cb_select"); // NOI18N
        cb_SelectLanguage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_SelectLanguageActionPerformed(evt);
            }
        });

        textarea_trans.setEditable(false);
        textarea_trans.setColumns(20);
        textarea_trans.setRows(5);
        jScrollPane1.setViewportView(textarea_trans);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE))
        );

        list_Suggest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_SuggestMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(list_Suggest);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Suggest");

        btn_Search.setText("Translate");
        btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_backroudLayout = new javax.swing.GroupLayout(pn_backroud);
        pn_backroud.setLayout(pn_backroudLayout);
        pn_backroudLayout.setHorizontalGroup(
            pn_backroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_backroudLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_backroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_backroudLayout.createSequentialGroup()
                        .addGroup(pn_backroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_backroudLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(pn_backroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cb_SelectLanguage, 0, 186, Short.MAX_VALUE)
                                    .addComponent(btn_Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_backroudLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(pn_backroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pn_backroudLayout.createSequentialGroup()
                        .addComponent(tf_KeyWord, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pn_backroudLayout.setVerticalGroup(
            pn_backroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_backroudLayout.createSequentialGroup()
                .addComponent(cb_SelectLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3))
            .addGroup(pn_backroudLayout.createSequentialGroup()
                .addComponent(tf_KeyWord, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setBackground(new java.awt.Color(51, 255, 51));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DICTIONNARY");

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pn_backroud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_backroud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void cb_SelectLanguageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_SelectLanguageActionPerformed
        if(cb_SelectLanguage.getSelectedItem().toString() == "English-Vietnamese"){
            Translation = 1;
        }
        if(cb_SelectLanguage.getSelectedItem().toString() == "Vietnamese - English"){
            Translation = 2;
        }
    }//GEN-LAST:event_cb_SelectLanguageActionPerformed

    private void btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchActionPerformed
        try {
            // DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
            //LocalDate localDate = LocalDate.now();
            textarea_trans.append("Đang gửi dữ liệu lên Server...\n");
            // Reset CHECKBOX
            //check_like.setSelected(false);
            //check_dislike.setSelected(false);
            //check_popular.setSelected(false);
            // Search KeyWOrd

            Socket ClientSocket = new Socket("Localhost", 1234);
            //tao luong nhan du lieu tu Server
            DataOutputStream outToServer = new DataOutputStream(ClientSocket.getOutputStream());
            outToServer.writeBytes(tf_KeyWord.getText() + '\n');
            DataInputStream inFromServer = new DataInputStream(ClientSocket.getInputStream());
            //tao luong gui du lieu len Server
            KeyWord = inFromServer.readLine();
            textarea_trans.append("Kết quả từ Server:" +KeyWord+"\n\n");

            if(Translation == 1){
                Meanings tempEN_VN =  Obj.LookUpEN_VN(KeyWord);
                if(tempEN_VN != null){
                    textarea_trans.setText(tempEN_VN.getPronunciation() + "\n"
                        + "--------------------------------------------------" + "\n"
                        + "* " + tempEN_VN.getAttribute() + "\n"
                        + tempEN_VN.getlistWordtrans());
                    // save history search
                    History temp = new History();
                    temp.setKey(KeyWord);
                    // temp.setDay(localDate.getDayOfMonth());
                    // temp.setMonth(localDate.getMonth().getValue());
                    //temp.setYear(localDate.getYear());
                    Obj.historyEN.add(temp);
                }
                else
                textarea_trans.setText("Nofound!!!");
            }
            else if(Translation == 2){
                Meanings tempVN_EN = Obj.lookUpVn_EN(KeyWord);
                if(tempVN_EN != null){
                    textarea_trans.setText(tempVN_EN.getPronunciation() + "\n"
                        + "--------------------------------------------------" + "\n"
                        + "* " + tempVN_EN.getAttribute() + "\n"
                        + tempVN_EN.getlistWordtrans());
                    // save History search
                    History temp = new History();
                    //temp.setKey(KeyWord);
                    // temp.setDay(localDate.getDayOfMonth());
                    // temp.setMonth(localDate.getMonth().getValue());
                    // temp.setYear(localDate.getYear());
                    Obj.historyVN.add(temp);
                }
                else
                textarea_trans.setText("Nofound!!!");
            }
            else{}

            // Check Other KeyWord EN
            
            //---------------------------------------------------------------------
            //CHECK OTHER KEY WORD
            
            //---------------------------------------------------------------------
        } catch (IOException ex) {
            Logger.getLogger(Dictionnary.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_SearchActionPerformed

    private void tf_KeyWordVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_tf_KeyWordVetoableChange

    }//GEN-LAST:event_tf_KeyWordVetoableChange

    private void tf_KeyWordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_KeyWordKeyReleased

        // Proc Enter
        KeyWord = tf_KeyWord.getText();
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btn_SearchActionPerformed(new java.awt.event.ActionEvent(btn_Search,0,""));
        }
        //  System.out.println(tf_KeyWord.getText());

        // EN - VN
        if(Translation == 1){
            list_Suggest.clearSelection();
            int count = 0;
            DefaultListModel listModel = new DefaultListModel();
            for(int i = 0; i < ProcessWord.listKey_EN_VN.size(); i++){
                if(ProcessWord.listKey_EN_VN.get(i).startsWith(KeyWord) == true){
                    listModel.addElement(ProcessWord.listKey_EN_VN.get(i));
                }
            }
            list_Suggest.setModel(listModel);
        }
        //VN - EN
        if(Translation == 2){
            list_Suggest.clearSelection();
            int count = 0;
            DefaultListModel listModel = new DefaultListModel();
            for(int i = 0; i < ProcessWord.listKey_VN_EN.size(); i++){
                if(ProcessWord.listKey_VN_EN.get(i).startsWith(KeyWord) == true){
                    listModel.addElement(ProcessWord.listKey_VN_EN.get(i));
                }
            }
            list_Suggest.setModel(listModel);
        }
    }//GEN-LAST:event_tf_KeyWordKeyReleased

    private void tf_KeyWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_KeyWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_KeyWordActionPerformed

    private void list_SuggestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_SuggestMouseClicked
        KeyWord = list_Suggest.getModel().getElementAt(list_Suggest.getSelectionModel().getAnchorSelectionIndex());
        tf_KeyWord.setText(KeyWord);
        btn_SearchActionPerformed(new java.awt.event.ActionEvent(btn_Search,0,""));
    }//GEN-LAST:event_list_SuggestMouseClicked

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        BufferedReader reader = null;
        try {
            String url = "D:\\content-niit\\file-content.txt";
            // Đọc dữ liệu từ File với File và FileReader
            File file = new File(url);
            reader = new BufferedReader(new FileReader(file));
            try {
                String line = reader.readLine();
                while (line != null) {
                    tf_KeyWord.setText(line);
                    //System.out.println(line);
                    line = reader.readLine();
                }
            } catch (FileNotFoundException ex) {
                
            } catch (IOException ex) {
                
            } finally {
                try {
                    reader.close();
                    
                } catch (IOException ex) {
                    
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Dictionnary.class.getName()).log(Level.SEVERE, null, ex);
            
        } finally {
            try {
                reader.close();
                
            } catch (IOException ex) {
                Logger.getLogger(Dictionnary.class.getName()).log(Level.SEVERE, null, ex);
               
            }
        }
        
    }//GEN-LAST:event_openMenuItemActionPerformed

    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dictionnary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dictionnary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dictionnary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dictionnary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Dictionnary().setVisible(true);
                Obj = new ProcessWord();
                Obj.ReadFile_EN_VN();
                Obj.ReadFileVN_EN();
                Obj.ReadFileListWordLove();
                Obj.ReadFileHistory();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Search;
    private javax.swing.JComboBox<String> cb_SelectLanguage;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> list_Suggest;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JPanel pn_backroud;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JTextArea textarea_trans;
    private javax.swing.JTextField tf_KeyWord;
    // End of variables declaration//GEN-END:variables

}
